name: Deploy Production

on:
  push:
    branches:
      - release/*

permissions:
  contents: read

# Allow only one concurrent deployment
concurrency:
  group: release
  cancel-in-progress: true

jobs:
  deploy-dark-prod:
    name: Deploy to Dark Prod 💥
    runs-on: ubuntu-latest
    environment: production
    env:
      VITE_STAGE: "${{ vars.VITE_STAGE }}"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 🚩
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4

      - name: Build
        run: echo "Building..."

  deploy-green-prod:
    name: Deploy to Green Prod 💥
    needs:
      - deploy-dark-prod
    runs-on: ubuntu-latest
    environment: production
    env:
      VITE_STAGE: "${{ vars.VITE_STAGE }}"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 🚩
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4

      - name: Build
        run: echo "Building..."

  release:
    name: Generate Release 💥
    runs-on: ubuntu-latest
    environment: production
    needs:
      - deploy-dark-prod
      - deploy-green-prod
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    env:
      VITE_STAGE: "${{ vars.VITE_STAGE }}"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 🚩
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4

      - name: Install 🎒
        run: pnpm install --prefer-offline --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build 📚
        run: pnpm build
        env:
          HUSKY: 0

      - name: Semantic Release 💥
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from release to main 🚀
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin $GITHUB_REF

          echo "GITHUB_REF: $GITHUB_REF"

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          DIFF_MAIN=$(git diff origin/main..origin/$BRANCH_NAME)

          if [ -z "$DIFF_MAIN" ]; then
            echo "No changes between branch $BRANCH_NAME and main. PR will not be created for main."
          else
            PR_EXISTS_MAIN=$(gh pr list --base main --head $BRANCH_NAME --json number --jq '.[].number')

            if [ -z "$PR_EXISTS_MAIN" ]; then
              gh pr create --base main --head $BRANCH_NAME --title "Release PR" --body "Automated PR with release updates." --label "semantic-release"
            else
              echo "PR already exists for this branch on main, PR number: $PR_EXISTS_MAIN"
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from release to staging 🚀
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin $GITHUB_REF

          echo "GITHUB_REF: $GITHUB_REF"

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          DIFF_STAGING=$(git diff origin/staging..origin/$BRANCH_NAME)

          if [ -z "$DIFF_STAGING" ]; then
            echo "No changes between branch $BRANCH_NAME and staging. PR will not be created for staging."
          else
            PR_EXISTS_STAGING=$(gh pr list --base staging --head $BRANCH_NAME --json number --jq '.[].number')

            if [ -z "$PR_EXISTS_STAGING" ]; then
              gh pr create --base staging --head $BRANCH_NAME --title "Release PR" --body "Automated PR with release updates." --label "semantic-release"
            else
              echo "PR already exists for this branch on staging, PR number: $PR_EXISTS_STAGING"
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
