name: Semantic Release

on:
  push:
    branches:
      - release/*

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    environment: staging
    env:
      VITE_STAGE: "${{ vars.VITE_STAGE }}"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup 🚩
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4

      - name: Install 🎒
        run: pnpm install --prefer-offline --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build 📚
        run: pnpm build
        env:
          HUSKY: 0

      - name: Release 💥
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for push completion ⏳
        run: sleep 10

      - name: Fetch latest changes
        run: |
          git fetch origin ${{ github.ref_name }}
          git pull

      - name: Open PR to Main 🚀
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: prepare release PR to main"
          title: "Release: Merge release branch into main"
          body: "This PR was automatically generated by the release workflow."
          base: ${{ github.ref_name }}
          branch: release-to-main/${{ github.ref_name }}

      - name: Open PR to Staging 🚀
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: prepare release PR to staging"
          title: "Release: Merge release branch into staging"
          body: "This PR was automatically generated by the release workflow."
          base: ${{ github.ref_name }}
          branch: release-to-staging/${{ github.ref_name }}
