name: Deploy Staging

on:
  push:
    branches:
      - staging

# Allow only one concurrent deployment
concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  deploy-dark:
    name: Deploy to Dark NonProd 💥
    runs-on: ubuntu-latest
    environment: dark-np
    env:
      VITE_STAGE: "${{ vars.VITE_STAGE }}"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 🚩
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4

      - name: Echo
        run: echo "🚀 Built s3://${{ env.VITE_STAGE }}"

  deploy-green:
    name: Deploy to Green NonProd 💥
    runs-on: ubuntu-latest
    needs:
      - deploy-dark
    environment: green-np
    env:
      VITE_STAGE: "${{ vars.VITE_STAGE }}"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 🚩
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4

      - name: Echo
        run: echo "🚀 Built s3://${{ env.VITE_STAGE }}"
